"""initial

Revision ID: 29defee39f2f
Revises:
Create Date: 2025-08-17 02:14:52.395227

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29defee39f2f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("mean_rate", sa.Float(precision=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="game_store",
    )
    op.create_table(
        "publishers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="game_store",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        schema="game_store",
    )
    op.create_index(
        op.f("ix_game_store_users_id"),
        "users",
        ["id"],
        unique=False,
        schema="game_store",
    )
    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["game_store.users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
        schema="game_store",
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Float(precision=2), nullable=False),
        sa.Column("release_date", sa.DateTime(), nullable=False),
        sa.Column("publisher_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "NES",
                "SNES",
                "N64",
                "GAMECUBE",
                "GAMEBOY",
                "GAMEBOY_COLOR",
                "GAMEBOY_ADVANCE",
                "DS",
                "MASTER_SYSTEM",
                "GENESIS",
                "SEGA_CD",
                "SATURN",
                "DREAMCAST",
                "GAME_GEAR",
                "PS1",
                "PS2",
                "PSP",
                "XBOX",
                "ATARI_2600",
                "ATARI_5200",
                "ATARI_7800",
                "ATARI_JAGUAR",
                "NEO_GEO",
                "NEO_GEO_POCKET",
                "TURBOGRAFX_16",
                "COMMODORE_64",
                "MSX",
                "MULTI",
                "OTHER",
                name="platformtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("is_digital", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "region",
            sa.Enum(
                "NTSC",
                "PAL",
                "NTSC_J",
                "NTSC_C",
                "NTSC_K",
                "NTSC_US",
                "PAL_B",
                "PAL_I",
                "REGION_FREE",
                name="regiontype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("condition_rating", sa.Integer(), nullable=True),
        sa.Column("has_original_box", sa.Boolean(), nullable=True),
        sa.Column("has_manual", sa.Boolean(), nullable=True),
        sa.Column("is_rare", sa.Boolean(), nullable=True),
        sa.Column("collector_value", sa.Float(precision=2), nullable=True),
        sa.Column("serial_number", sa.String(length=100), nullable=True),
        sa.Column("special_edition", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["publisher_id"], ["game_store.publishers.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_index(
        op.f("ix_game_store_games_title"),
        "games",
        ["title"],
        unique=False,
        schema="game_store",
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                "REFUNDED",
                name="orderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("total_amount", sa.Float(precision=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["game_store.users.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["game_store.carts.id"]),
        sa.ForeignKeyConstraint(["game_id"], ["game_store.games.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_table(
        "game_genre",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game_store.games.id"]),
        sa.ForeignKeyConstraint(["genre_id"], ["game_store.genres.id"]),
        sa.PrimaryKeyConstraint("game_id", "genre_id"),
        schema="game_store",
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(precision=2), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game_store.games.id"]),
        sa.ForeignKeyConstraint(["order_id"], ["game_store.orders.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["game_store.games.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["game_store.users.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_table(
        "web_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("time_spent", sa.Integer(), nullable=True),
        sa.Column("referrer_page", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("search_query", sa.String(), nullable=True),
        sa.Column("filters_applied", sa.String(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["game_store.games.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["game_store.users.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="game_store",
    )
    op.create_index(
        op.f("ix_game_store_web_events_id"),
        "web_events",
        ["id"],
        unique=False,
        schema="game_store",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_game_store_web_events_id"),
        table_name="web_events",
        schema="game_store",
    )
    op.drop_table("web_events", schema="game_store")
    op.drop_table("reviews", schema="game_store")
    op.drop_table("order_items", schema="game_store")
    op.drop_table("game_genre", schema="game_store")
    op.drop_table("cart_items", schema="game_store")
    op.drop_table("orders", schema="game_store")
    op.drop_index(
        op.f("ix_game_store_games_title"),
        table_name="games",
        schema="game_store",
    )
    op.drop_table("games", schema="game_store")
    op.drop_table("carts", schema="game_store")
    op.drop_index(
        op.f("ix_game_store_users_id"),
        table_name="users",
        schema="game_store",
    )
    op.drop_table("users", schema="game_store")
    op.drop_table("publishers", schema="game_store")
    op.drop_table("genres", schema="game_store")
    # ### end Alembic commands ###
