version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data
  postgres:
    image: postgres:17-alpine3.20
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
  fastapi:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
