global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'application'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.17.0.1:8001']
        labels:
          service: 'real-time-api'
          environment: 'production'